### ISSUE TITLE
License

### ISSUE THREAD

**Issue by colinhumber** [croberts22/CRNavigationController#3]
What's the license for this?

**Comment by croberts22** [comment]
MIT License.

**Comment by colinhumber** [comment]
Can you add the license file to the repo? Without an explicit license on the repo the code falls back to All Rights Reserved. https://help.github.com/articles/open-source-licensing#what-happens-if-i-dont-choose-a-license

Thanks

**Comment by croberts22** [comment]
Ah good catch, thanks!

**Comment by colinhumber** [comment]
No prob! Thanks for putting this up!
