### ISSUE TITLE
iOS 7.0.3

### ISSUE THREAD

**Issue by walteryaron** [croberts22/CRNavigationController#5]
In iOS 7.0.3 it seems like Apple solve the blur problem and bartintcolor and now we don't need this solution.
Can you confirm this ?

**Comment by croberts22** [comment]
This solution is still very much usable for any devices running iOS 7.0.2 and less. I am currently updating the library so that it handles all iOS 7 versions.

**Comment by walteryaron** [comment]
Thanks for your great work , just want to help you :)
